# Generated by Django 3.0.9 on 2020-08-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='item',
            new_name='text',
        ),
    ]
